#@ load("@ytt:data", "data")

---
apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: contour-delegation
  namespace: #@ data.values.tls.namespace
spec:
  delegations:
    - secretName: #@ data.values.tls.secretName
      targetNamespaces:
        - "*"

---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: app-live-view
  namespace: app-live-view
spec:
  virtualhost:
    fqdn: #@ "app-live-view.{}".format(data.values.domain)
    tls:
      secretName: #@ "{}/{}".format(data.values.tls.namespace,data.values.tls.secretName)
  routes:
    - services:
        - name: application-live-view-5112
          port: 80

